import { Navbar, Footer } from "@/components";
import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "@/providers/QueryProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen w-full flex flex-col justify-between items-center">
          <Navbar />
          <div>
            <QueryProvider>{children}</QueryProvider>
          </div>
          <Footer />
        </main>
      </body>
    </html>
  );
}
